import { app, BrowserWindow, globalShortcut, screen, Tray, Menu, nativeImage, ipcMain } from 'electron';
import * as path from 'path';
import * as fs from 'fs';

const MARGIN = 24;
const SIZE = 360; // default overlay size on a first launch
const MIN_SIZE = 120;
const MAX_SIZE = 1000;

let win: BrowserWindow;
let settingsWin: BrowserWindow | null = null;
let tray: Tray;
let fullscreen = false;
let dragOffsetX = 0;
let dragOffsetY = 0;

// ponytail: main owns the settings because two windows cannot share
// localStorage reliably. One JSON file, read once, rewritten on every change —
// it is a handful of numbers, a debounce or a store dependency would cost more
// than it saves.
type Settings = {
  threshold: number;
  drain: number;
  refill: number;
  sound: boolean;
  micId: string;
  size: number; // overlay side length in px (square), set by the size slider
};
const CONFIG = path.join(app.getPath('userData'), 'settings.json');
// drain/refill defaults duplicated from levels.ts (DRAIN_SECONDS /
// REFILL_SECONDS): levels.ts is a global script with no exports on purpose, and
// two numbers are cheaper than making it importable from the main process.
const DEFAULTS: Settings = { threshold: 0.5, drain: 20, refill: 40, sound: false, micId: '', size: SIZE };
let settings: Settings = DEFAULTS;
// last mic list the overlay reported; replayed into the settings window when it
// opens, so the overlay never has to be asked for it.
let lastMics: unknown[] = [];

// the slider bounds are markup, and settings.json is hand-editable, so the one
// value that sizes a real window is clamped on the way in from both.
function clampSize(n: number): number {
  return Math.max(MIN_SIZE, Math.min(MAX_SIZE, Math.round(Number(n) || SIZE)));
}

function loadSettings(): void {
  try {
    settings = { ...DEFAULTS, ...JSON.parse(fs.readFileSync(CONFIG, 'utf8')) };
    settings.size = clampSize(settings.size);
  } catch {
    settings = DEFAULTS; // missing or corrupt file: defaults, not a crash
  }
}

function saveSettings(): void {
  try {
    fs.writeFileSync(CONFIG, JSON.stringify(settings));
  } catch (e) {
    console.error('failed to write settings', e);
  }
}

// ponytail: generated by `npm run icon` from the same cat SVG src/index.html
// shows, so tray/app icon and mascot never drift apart.
function trayIcon(): Electron.NativeImage {
  return nativeImage
    .createFromPath(path.join(__dirname, '..', 'build', 'icon.png'))
    .resize({ width: 16, height: 16 });
}

function toggleSettings(): void {
  if (settingsWin) {
    settingsWin.close();
    return;
  }
  settingsWin = new BrowserWindow({
    width: 440,
    height: 780,
    title: 'Réglages — noise-overlay',
    backgroundColor: '#101923', // --hcds-surface, dark theme (src/tokens.css)
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });
  settingsWin.setMenuBarVisibility(false);
  settingsWin.loadFile(path.join(__dirname, '..', 'src', 'settings.html'));
  settingsWin.webContents.on('did-finish-load', () => {
    settingsWin?.webContents.send('mics', lastMics);
  });
  settingsWin.on('closed', () => {
    settingsWin = null;
    markSettingsOpen();
    buildTrayMenu();
  });
  markSettingsOpen();
  buildTrayMenu();
}

// ponytail: same trick fullscreen already used — a body class poked into the
// overlay, no extra IPC channel just to tick one ✓ in the in-page menu.
function markSettingsOpen(): void {
  win.webContents.executeJavaScript(
    `document.body.classList.toggle('settings-open', ${settingsWin !== null})`,
  );
}

function toggleFullscreen(): void {
  fullscreen = !win.isFullScreen();
  win.setFullScreen(fullscreen);
  win.webContents.executeJavaScript(`document.body.classList.toggle('fullscreen', ${fullscreen})`);
  buildTrayMenu();
}

// tray only: the cat's own right-click menu is drawn in the page (index.html
// #ctxmenu), because a native menu's look is entirely OS-controlled and this
// one has to match the app. The tray lives outside the window, so it stays native.
function buildTrayMenu(): void {
  const menu = Menu.buildFromTemplate([
    { label: 'Plein écran', type: 'checkbox', checked: fullscreen, click: toggleFullscreen },
    { label: 'Réglages', type: 'checkbox', checked: settingsWin !== null, click: toggleSettings },
    { type: 'separator' },
    { label: 'Quitter', click: () => app.quit() },
  ]);
  tray.setContextMenu(menu);
}

// where the overlay starts, and where "réinitialiser la position" puts it back.
// Recomputed on every call rather than stored: the work area changes when a
// projector is plugged in or unplugged, which is exactly when the cat ends up
// off-screen and someone reaches for the button.
function homePosition(size: number): { x: number; y: number } {
  const { width: sw, height: sh } = screen.getPrimaryDisplay().workAreaSize;
  return { x: sw - size - MARGIN, y: sh - size - MARGIN };
}

function resetPosition(): void {
  if (win.isFullScreen()) return; // nothing to move: it covers the screen
  const size = settings.size;
  // setBounds with the size restated, same reason as drag-move below.
  win.setBounds({ ...homePosition(size), width: size, height: size });
}

function createWindow(): void {
  const size = settings.size; // restored size, so the corner anchor still lands right
  win = new BrowserWindow({
    width: size,
    height: size,
    ...homePosition(size),
    frame: false,
    transparent: true,
    backgroundColor: '#00000000',
    alwaysOnTop: true,
    skipTaskbar: true,
    // resizable must stay true: on Windows a non-resizable window refuses to
    // go fullscreen. Frameless means there is no visible resize border anyway.
    resizable: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });
  win.setAlwaysOnTop(true, 'screen-saver');
  // ponytail: resizable stays true for fullscreen (above), so Windows keeps an
  // invisible grab border on the frameless edges. Refuse the gesture instead of
  // the capability — will-resize only fires for user drags, setSize is untouched,
  // so the settings slider still works.
  win.on('will-resize', (event) => {
    if (!win.isFullScreen()) event.preventDefault();
  });
  win.loadFile(path.join(__dirname, '..', 'src', 'index.html'));
}

// ponytail: -webkit-app-region: drag and a working right-click are mutually
// exclusive on Windows, so dragging is done by hand here instead. drag-start
// captures the cursor-to-window offset once, drag-move just replays raw cursor
// coordinates against it. The rest is the two-window plumbing: settings live in
// main, live meters travel overlay -> main -> settings window.
function registerIPC(): void {
  // one channel for the in-page menu, carrying the action name — same three
  // actions as the tray menu.
  ipcMain.on('menu-action', (_event, action: string) => {
    if (action === 'fullscreen') toggleFullscreen();
    else if (action === 'settings') toggleSettings();
    else if (action === 'reset-position') resetPosition();
    else if (action === 'quit') app.quit();
  });
  ipcMain.on('drag-start', () => {
    const cursor = screen.getCursorScreenPoint();
    const [wx, wy] = win.getPosition();
    dragOffsetX = cursor.x - wx;
    dragOffsetY = cursor.y - wy;
  });
  ipcMain.on('drag-move', (_event, x: number, y: number) => {
    // setBounds, not setPosition: dragging across monitors with different DPI
    // scales makes the size drift, and every mouse event compounds it — the cat
    // grew while the button was held. Restating width/height each move pins it.
    // Rounded because these are fractional in CSS px on a scaled display, and
    // the API only takes integers ("conversion failure" mid-drag otherwise).
    const size = settings.size;
    win.setBounds({
      x: Math.round(x - dragOffsetX),
      y: Math.round(y - dragOffsetY),
      width: size,
      height: size,
    });
  });

  ipcMain.handle('settings-get', () => settings);
  ipcMain.on('settings-set', (_event, next: Settings) => {
    settings = { ...next, size: clampSize(next.size) };
    saveSettings();
    // the overlay is square and has no grab border of its own; the size slider
    // is what resizes it. Skipped in fullscreen — leaving fullscreen restores
    // the windowed size anyway.
    if (!win.isFullScreen()) win.setSize(settings.size, settings.size);
    win.webContents.send('settings', settings);
  });
  // no-ops while the settings window is closed, so the overlay never has to be
  // told to stop sending.
  ipcMain.on('meters', (_event, m: unknown) => settingsWin?.webContents.send('meters', m));
  ipcMain.on('mics', (_event, list: unknown[]) => {
    lastMics = list;
    settingsWin?.webContents.send('mics', list);
  });
}

// ponytail: one classroom, one cat. Two overlays would fight over the mic, the
// global shortcuts and settings.json. A second launch just shows the first —
// the app is skipTaskbar, so double-clicking the exe again is what a teacher
// does when they think it did not start.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) app.quit();

app.on('second-instance', () => {
  win.show();
  win.focus();
});

app.whenReady().then(() => {
  if (!gotLock) return; // quit is already in flight
  loadSettings();
  createWindow();
  registerIPC();

  tray = new Tray(trayIcon());
  tray.setToolTip('noise-overlay');
  tray.on('click', toggleSettings);
  buildTrayMenu();

  const okSettings = globalShortcut.register('Control+Shift+P', toggleSettings);
  if (!okSettings) console.error('failed to register Ctrl+Shift+P (settings toggle)');

  const okFullscreen = globalShortcut.register('Control+Shift+F', toggleFullscreen);
  if (!okFullscreen) console.error('failed to register Ctrl+Shift+F (fullscreen toggle)');

  const okQuit = globalShortcut.register('Control+Shift+Q', () => app.quit());
  if (!okQuit) console.error('failed to register Ctrl+Shift+Q (quit)');
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});

// closing the settings window leaves the overlay open, so this still only fires
// when the overlay itself is gone — quitting then is right.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
