import { app, BrowserWindow, globalShortcut, screen, Tray, Menu, nativeImage, ipcMain } from 'electron';
import * as path from 'path';

const MARGIN = 24;
const SIZE = 360;
const PANEL_SIZE = 720; // the settings panel needs room the overlay does not

let win: BrowserWindow;
let tray: Tray;
let interactive = false;
let fullscreen = false;
let dragOffsetX = 0;
let dragOffsetY = 0;

// ponytail: generated by `npm run icon` from the same cat SVG src/index.html
// shows, so tray/app icon and mascot never drift apart.
function trayIcon(): Electron.NativeImage {
  return nativeImage
    .createFromPath(path.join(__dirname, '..', 'build', 'icon.png'))
    .resize({ width: 16, height: 16 });
}

function toggleInteractive(): void {
  interactive = !interactive;
  win.setSize(interactive ? PANEL_SIZE : SIZE, interactive ? PANEL_SIZE : SIZE);
  win.webContents.executeJavaScript(`document.body.classList.toggle('interactive', ${interactive})`);
  buildTrayMenu();
}

function toggleFullscreen(): void {
  fullscreen = !win.isFullScreen();
  win.setFullScreen(fullscreen);
  win.webContents.executeJavaScript(`document.body.classList.toggle('fullscreen', ${fullscreen})`);
  buildTrayMenu();
}

// tray only: the cat's own right-click menu is drawn in the page (index.html
// #ctxmenu), because a native menu's look is entirely OS-controlled and this
// one has to match the app. The tray lives outside the window, so it stays native.
function buildTrayMenu(): void {
  const menu = Menu.buildFromTemplate([
    { label: 'Plein écran', type: 'checkbox', checked: fullscreen, click: toggleFullscreen },
    { label: 'Réglages', type: 'checkbox', checked: interactive, click: toggleInteractive },
    { type: 'separator' },
    { label: 'Quitter', click: () => app.quit() },
  ]);
  tray.setContextMenu(menu);
}

function createWindow(): void {
  const { width: sw, height: sh } = screen.getPrimaryDisplay().workAreaSize;
  win = new BrowserWindow({
    width: SIZE,
    height: SIZE,
    x: sw - SIZE - MARGIN,
    y: sh - SIZE - MARGIN,
    frame: false,
    transparent: true,
    backgroundColor: '#00000000',
    alwaysOnTop: true,
    skipTaskbar: true,
    // resizable must stay true: on Windows a non-resizable window refuses to
    // go fullscreen. Frameless means there is no visible resize border anyway.
    resizable: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });
  win.setAlwaysOnTop(true, 'screen-saver');
  win.loadFile(path.join(__dirname, '..', 'src', 'index.html'));
}

// ponytail: -webkit-app-region: drag and a working right-click are mutually
// exclusive on Windows, so dragging is done by hand here instead — the one
// deliberate exception to "no preload, no IPC" in this app. Kept to two
// fire-and-forget messages: drag-start captures the cursor-to-window offset
// once, drag-move just replays raw cursor coordinates against it.
function registerIPC(): void {
  // one channel for the in-page menu, carrying the action name — same three
  // actions as the tray menu.
  ipcMain.on('menu-action', (_event, action: string) => {
    if (action === 'fullscreen') toggleFullscreen();
    else if (action === 'settings') toggleInteractive();
    else if (action === 'quit') app.quit();
  });
  ipcMain.on('drag-start', () => {
    const cursor = screen.getCursorScreenPoint();
    const [wx, wy] = win.getPosition();
    dragOffsetX = cursor.x - wx;
    dragOffsetY = cursor.y - wy;
  });
  ipcMain.on('drag-move', (_event, x: number, y: number) => {
    win.setPosition(x - dragOffsetX, y - dragOffsetY);
  });
}

app.whenReady().then(() => {
  createWindow();
  registerIPC();

  tray = new Tray(trayIcon());
  tray.setToolTip('noise-overlay');
  tray.on('click', toggleInteractive);
  buildTrayMenu();

  const okInteractive = globalShortcut.register('Control+Shift+P', toggleInteractive);
  if (!okInteractive) console.error('failed to register Ctrl+Shift+P (interactive toggle)');

  const okFullscreen = globalShortcut.register('Control+Shift+F', toggleFullscreen);
  if (!okFullscreen) console.error('failed to register Ctrl+Shift+F (fullscreen toggle)');

  const okQuit = globalShortcut.register('Control+Shift+Q', () => app.quit());
  if (!okQuit) console.error('failed to register Ctrl+Shift+Q (quit)');
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
